name: Deploy Blazor to GitHub Pages

on:
  push:
  tags:
      - 'v*'  # matches v1, v1.0.0, v2.1.5, etc.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.x

    - name: Publish
      run: dotnet publish -c Release -o release

    - name: Copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: release/wwwroot
